name: "CI/CD"
on: 
  push:
  pull_request:
    branches:
    - main
 
jobs:
  CI:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v4
        with:
          java-version: 17.0
          distribution: zulu
          cache: maven
      - name: Compile
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Enterprise
        uses: actions/upload-artifact@v4
        with:
          name: Kauri with Detections
          path: target/EnterpriseAnticheat-*.jar
